### ISSUE TITLE
hnsw和hnsw_original的区别是什么？add和balanced_add的区别是什么？哪一种更好？

### ISSUE THREAD

**Issue by qxzhou1010** [RyanLiGod/hnsw-python#1]
你好，拜读了你的代码，感觉非常好，想请问下hnsw和hnsw_original的区别是什么？add和balanced_add的区别是什么？哪一种更好？

**Comment by RyanLiGod** [comment]
没有original的我在修改的，我在hnsw基础上实现自己的改进方法，但是是半成品，但后来用go语言实现了。你用original才是原来的hnsw方法。balanced_add是改善随机分层可能导致不平衡的问题，然后如果一个结点的邻居都没有在上层出现，那么就把这个结点加入到上层。原仓库链接已经在另一个issue给你了，里面有解释。
